light_guide:
  # options (string): rectangle, polygon
  geometry: polygon 
  n_sides: 4
  dimensions_in_mm: [330.0, 10.0, 330.0] 
  wls: TPB
  BBT_concentration: 1

sipm:
  dimensions_in_mm: [6.0, 6.0, 1.0]
  # options (string): left_right, top_bottom, all
  placement: all
  number: 10
  gap_in_mm: 0

external_wls:
  # options (string): null or TPB, PEN, pTP
  material: null
  thickness_in_mm: 1 
  gap_in_mm: 1  

reflector: 
  placement: True
  # gap_in_mm: None
