/RMG/Manager/Logging/LogLevel detail

/RMG/Processes/OpticalPhysics true
/RMG/Processes/OpticalPhysicsMaxOneWLSPhoton true

/RMG/Geometry/RegisterDetector Optical sipm_.* 00

###/RMG/Output/ActivateOutputScheme Track
/RMG/Output/ActivateOutputScheme LGOutputScheme

/run/initialize

/RMG/Output/NtuplePerDetector false
###/RMG/Output/Track/StoreOpticalPhotons true
/RMG/Output/FileName beam_TPB.root

/RMG/Generator/Select GPS
/gps/particle opticalphoton
/gps/pos/centre 0 0.7 0 m
/gps/direction 0 -1 0
/gps/energy 9.69 eV      # 128nm, LAr peak emission
/run/beamOn 10000000