/RMG/Manager/Logging/LogLevel detail

/RMG/Processes/OpticalPhysics true
/RMG/Processes/OpticalPhysicsMaxOneWLSPhoton true

/RMG/Geometry/RegisterDetector Optical sipm_.* 00

####/RMG/Output/ActivateOutputScheme Track
/RMG/Output/ActivateOutputScheme LGOutputScheme

/run/initialize

/RMG/Output/NtuplePerDetector false
###/RMG/Output/Track/StoreOpticalPhotons true
/RMG/Output/FileName testing.root

/RMG/Generator/Select GPS
/gps/particle opticalphoton
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 0.3 0 m
/gps/pos/halfx 800 mm
/gps/pos/halfy 250 mm
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 -1

/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg
/gps/ang/minphi 0 deg
/gps/ang/maxphi 360 deg
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 0 -1

/gps/energy 9.69 eV      # 128nm, LAr peak emission
########/gps/energy 7.09 eV      # 175nm, Xe-doped LAr peak emission

/run/beamOn 10000000